### ISSUE TITLE
Xbox 360, Xbox original

### ISSUE THREAD

**Issue by Torinde** [WinDurango/WinDurango#2]
As much more software is available for Xbox 360 and Xbox original - is it feasible to add wrappers for those environments?

Xbox 360 will need also to emulate PowerPC, probably solvable by lifting code from Xenia, QEMU or another PPC emulator. Example of cross-architecture wrapper is [EmuWoW](https://github.com/BHTY/EmuWoW) (running Win32 MIPS and Alpha programs on x86 Windows).

**Comment by TylerJaacks** [comment]
the point of this project is not to emulator the Xbox Original or Xbox 360 you can refer to xemue or Xenia for those platforms respectively. This project is for the Xbox One.

**Comment by TylerJaacks** [comment]
The Xbox Original is no where near the same as the Xbox Original or Xbox 360. The Xbox One is an x86 system that runs the Hyper-V hypervisor that runs three virtualized windows installations. https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi3.ruliweb.com%2Fimg%2F20%2F10%2F02%2F174e78a90be50eb19.jpg&f=1&nofb=1&ipt=0fdaa2a122122acfc26ee774236798774befc0cd9e911b0290df622488dd2a07&ipo=images and you can read more about it here https://xboxoneresearch.github.io/wiki/operating-system/xbox-operating-system/

**Comment by TylerJaacks** [comment]
The later

**Comment by upintheairsheep** [comment]
Xbox Original/360 emulators developed by MS might be able to run.
